"""Team style clustering — production interface.

Provides functions to compute team style features from the DB and look up
which style cluster (archetype) a team belongs to.

The cluster model is generated by analysis/03_clustering.ipynb and must
be run before this module can assign clusters.
"""
from __future__ import annotations

import json
import pickle
import sqlite3
from pathlib import Path

import numpy as np

from config import NBA_TEAM_MAP, INITIAL_SEASON

_MODEL_PATH = Path(__file__).parent / "cluster_model.pkl"
_META_PATH = Path(__file__).parent / "cluster_model_meta.json"

_cached_model: dict | None = None  # lazy loading


def _load_model() -> dict:
    """Load the cluster model from disk, caching in memory after first load.

    Returns the model dict containing 'scaler', 'pca', 'kmeans', and 'feature_names'.

    Raises:
        FileNotFoundError: if cluster_model.pkl does not exist.
    """
    global _cached_model
    if _cached_model is None:
        if not _MODEL_PATH.exists():
            raise FileNotFoundError(
                f"Cluster model not found at {_MODEL_PATH}. "
                "Run analysis/03_clustering.ipynb first to generate the model."
            )
        with open(_MODEL_PATH, "rb") as f:
            _cached_model = pickle.load(f)
    return _cached_model


def _gini_coefficient(values: list[float]) -> float:
    """Compute Gini coefficient for a list of non-negative values.

    Returns 0.0 if the list is empty or all values are zero.
    """
    arr = sorted(values)
    n = len(arr)
    if n == 0 or sum(arr) == 0:
        return 0.0
    idx = range(1, n + 1)
    return (2 * sum(i * v for i, v in zip(idx, arr))) / (n * sum(arr)) - (n + 1) / n


def compute_team_features(
    conn: sqlite3.Connection,
    team_id: str,
    season: str = INITIAL_SEASON,
) -> dict[str, float]:
    """Compute all 18 style features for a single team from the DB.

    Uses full-season data up to the latest available game.
    Returns raw (unnormalized) feature values.

    Feature names:
        three_pt_attempt_rate, three_pt_pct, two_pt_pct, ft_point_rate,
        fga_per_possession, turnover_rate, oreb_rate, transition_rate, off_rating,
        opp_three_pt_attempt_rate, opp_two_pt_pct, opp_turnover_rate, opp_oreb_rate,
        def_rating, avg_pace, weighted_off_rapm, star_concentration, rotation_depth

    Args:
        conn: open SQLite connection with row_factory set or not (handles both).
        team_id: nba.com team ID string.
        season: season string, e.g. "2025-26".

    Returns:
        dict mapping feature name → float value.

    Raises:
        ValueError: if the team has fewer than 50 offensive possessions.
    """
    cur = conn.cursor()

    # ------------------------------------------------------------------
    # Guard: minimum possession count
    # ------------------------------------------------------------------
    cur.execute(
        "SELECT COUNT(*) FROM possessions WHERE season = ? AND offense_team_id = ?",
        (season, team_id),
    )
    row = cur.fetchone()
    poss_count = row[0] if row else 0
    if poss_count < 50:
        raise ValueError(
            f"Team {team_id} has insufficient data for feature computation "
            f"(only {poss_count} offensive possessions in season {season})"
        )

    # ------------------------------------------------------------------
    # Offensive features
    # ------------------------------------------------------------------
    cur.execute(
        """
        SELECT
            CAST(SUM(fg3a) AS REAL) / NULLIF(SUM(fg2a) + SUM(fg3a), 0) AS three_pt_attempt_rate,
            CAST(SUM(fg3m) AS REAL) / NULLIF(SUM(fg3a), 0)              AS three_pt_pct,
            CAST(SUM(fg2m) AS REAL) / NULLIF(SUM(fg2a), 0)              AS two_pt_pct,
            CAST(SUM(free_throw_points) AS REAL) / NULLIF(SUM(points_scored), 0) AS ft_point_rate,
            CAST(SUM(fg2a) + SUM(fg3a) AS REAL) / COUNT(*)              AS fga_per_possession,
            CAST(SUM(turnovers) AS REAL) / COUNT(*)                     AS turnover_rate,
            CAST(SUM(offensive_rebounds) AS REAL) / COUNT(*)            AS oreb_rate,
            CAST(SUM(CASE WHEN start_type = 'OffLiveBallTurnover' THEN 1 ELSE 0 END) AS REAL) / COUNT(*) AS transition_rate,
            CAST(SUM(points_scored) AS REAL) / COUNT(*) * 100           AS off_rating
        FROM possessions
        WHERE season = ? AND offense_team_id = ?
        """,
        (season, team_id),
    )
    off_row = cur.fetchone()

    def _coerce(v: object, default: float = 0.0) -> float:
        """Return float(v) or default if v is None."""
        return float(v) if v is not None else default

    # off_row may be a sqlite3.Row or a plain tuple; index by position
    three_pt_attempt_rate = _coerce(off_row[0])
    three_pt_pct          = _coerce(off_row[1])
    two_pt_pct            = _coerce(off_row[2])
    ft_point_rate         = _coerce(off_row[3])
    fga_per_possession    = _coerce(off_row[4])
    turnover_rate         = _coerce(off_row[5])
    oreb_rate             = _coerce(off_row[6])
    transition_rate       = _coerce(off_row[7])
    off_rating            = _coerce(off_row[8])

    # ------------------------------------------------------------------
    # Defensive features
    # ------------------------------------------------------------------
    cur.execute(
        """
        SELECT
            CAST(SUM(fg3a) AS REAL) / NULLIF(SUM(fg2a) + SUM(fg3a), 0) AS opp_three_pt_attempt_rate,
            CAST(SUM(fg2m) AS REAL) / NULLIF(SUM(fg2a), 0)              AS opp_two_pt_pct,
            CAST(SUM(turnovers) AS REAL) / COUNT(*)                     AS opp_turnover_rate,
            CAST(SUM(offensive_rebounds) AS REAL) / COUNT(*)            AS opp_oreb_rate,
            CAST(SUM(points_scored) AS REAL) / COUNT(*) * 100           AS def_rating
        FROM possessions
        WHERE season = ? AND defense_team_id = ?
        """,
        (season, team_id),
    )
    def_row = cur.fetchone()

    opp_three_pt_attempt_rate = _coerce(def_row[0])
    opp_two_pt_pct            = _coerce(def_row[1])
    opp_turnover_rate         = _coerce(def_row[2])
    opp_oreb_rate             = _coerce(def_row[3])
    def_rating                = _coerce(def_row[4])

    # ------------------------------------------------------------------
    # Pace: average of home + away game_pace for this team
    # ------------------------------------------------------------------
    cur.execute(
        """
        SELECT AVG(game_pace) AS avg_pace
        FROM (
            SELECT game_pace FROM games WHERE season = ? AND home_team_id = ?
            UNION ALL
            SELECT game_pace FROM games WHERE season = ? AND away_team_id = ?
        )
        """,
        (season, team_id, season, team_id),
    )
    pace_row = cur.fetchone()
    avg_pace = _coerce(pace_row[0], default=100.0)

    # ------------------------------------------------------------------
    # Player composition features
    # ------------------------------------------------------------------
    cur.execute(
        """
        WITH all_players AS (
            SELECT off_player_1 AS player_id FROM possessions WHERE season = ? AND offense_team_id = ?
            UNION ALL SELECT off_player_2 FROM possessions WHERE season = ? AND offense_team_id = ?
            UNION ALL SELECT off_player_3 FROM possessions WHERE season = ? AND offense_team_id = ?
            UNION ALL SELECT off_player_4 FROM possessions WHERE season = ? AND offense_team_id = ?
            UNION ALL SELECT off_player_5 FROM possessions WHERE season = ? AND offense_team_id = ?
        )
        SELECT player_id, COUNT(*) AS poss_count
        FROM all_players
        GROUP BY player_id
        HAVING COUNT(*) >= 100
        ORDER BY poss_count DESC
        """,
        (
            season, team_id,
            season, team_id,
            season, team_id,
            season, team_id,
            season, team_id,
        ),
    )
    player_rows = cur.fetchall()

    if player_rows:
        player_ids = [r[0] for r in player_rows]
        raw_counts = [r[1] for r in player_rows]
        total_counts = sum(raw_counts)
        shares: dict[str, float] = {
            pid: cnt / total_counts for pid, cnt in zip(player_ids, raw_counts)
        }

        # Fetch offense ratings for these players
        placeholders = ",".join("?" * len(player_ids))
        cur.execute(
            f"SELECT player_id, offense FROM current_ratings WHERE season = ? AND player_id IN ({placeholders})",
            (season, *player_ids),
        )
        rating_rows = cur.fetchall()
        ratings: dict[str, float] = {r[0]: float(r[1]) for r in rating_rows}

        weighted_off_rapm = sum(
            shares[pid] * ratings[pid]
            for pid in player_ids
            if pid in ratings
        )
        star_concentration = _gini_coefficient(list(shares.values()))
        rotation_depth = sum(1 for share in shares.values() if share > 0.06)
    else:
        # Fallback: no player passed the 100-possession threshold
        weighted_off_rapm = 0.0
        star_concentration = 0.0
        rotation_depth = 0

    return {
        "three_pt_attempt_rate":     three_pt_attempt_rate,
        "three_pt_pct":              three_pt_pct,
        "two_pt_pct":                two_pt_pct,
        "ft_point_rate":             ft_point_rate,
        "fga_per_possession":        fga_per_possession,
        "turnover_rate":             turnover_rate,
        "oreb_rate":                 oreb_rate,
        "transition_rate":           transition_rate,
        "off_rating":                off_rating,
        "opp_three_pt_attempt_rate": opp_three_pt_attempt_rate,
        "opp_two_pt_pct":            opp_two_pt_pct,
        "opp_turnover_rate":         opp_turnover_rate,
        "opp_oreb_rate":             opp_oreb_rate,
        "def_rating":                def_rating,
        "avg_pace":                  avg_pace,
        "weighted_off_rapm":         weighted_off_rapm,
        "star_concentration":        star_concentration,
        "rotation_depth":            float(rotation_depth),
    }


def get_team_cluster(
    conn: sqlite3.Connection,
    team_id: str,
    season: str = INITIAL_SEASON,
) -> int:
    """Compute features for team_id, apply StandardScaler + PCA + KMeans from the
    saved model, and return the cluster ID (0-indexed integer).

    Args:
        conn: open SQLite connection.
        team_id: nba.com team ID string.
        season: season string, e.g. "2025-26".

    Returns:
        Cluster ID as a 0-indexed integer.

    Raises:
        FileNotFoundError: if downstream/cluster_model.pkl does not exist.
        ValueError: if team_id has insufficient possession data (< 50 possessions).
    """
    model = _load_model()
    features = compute_team_features(conn, team_id, season)
    feature_names: list[str] = model["feature_names"]
    X = np.array([[features[f] for f in feature_names]])
    X_scaled = model["scaler"].transform(X)
    X_pca = model["pca"].transform(X_scaled)
    cluster_id = int(model["kmeans"].predict(X_pca)[0])
    return cluster_id


def get_all_team_clusters(
    conn: sqlite3.Connection,
    season: str = INITIAL_SEASON,
) -> dict[str, int]:
    """Return {team_id: cluster_id} for all 30 teams with sufficient data.

    Teams with fewer than 50 offensive possessions (or any other error during
    feature computation) are silently omitted from the result.

    Args:
        conn: open SQLite connection.
        season: season string, e.g. "2025-26".

    Returns:
        dict mapping team_id → cluster_id for every team that has enough data.
    """
    results: dict[str, int] = {}
    for team_id in NBA_TEAM_MAP:
        try:
            cluster_id = get_team_cluster(conn, team_id, season)
            results[team_id] = cluster_id
        except (ValueError, Exception):
            pass  # team with insufficient data or other transient error
    return results


def get_cluster_name(cluster_id: int) -> str:
    """Return the human-readable cluster name from cluster_model_meta.json.

    Falls back to 'Cluster {id}' if the meta file does not exist or the
    name key is not present for the given cluster_id.

    Args:
        cluster_id: 0-indexed integer cluster ID.

    Returns:
        Human-readable name string.
    """
    if not _META_PATH.exists():
        return f"Cluster {cluster_id}"
    try:
        with open(_META_PATH, "r", encoding="utf-8") as f:
            meta: dict = json.load(f)
        # Expected structure: {"cluster_names": {0: "Fast-Paced 3-Point", ...}}
        # Keys may be stored as strings in JSON
        names: dict = meta.get("cluster_names", {})
        name = names.get(cluster_id) or names.get(str(cluster_id))
        if name:
            return str(name)
    except (json.JSONDecodeError, KeyError, TypeError):
        pass
    return f"Cluster {cluster_id}"


# ---------------------------------------------------------------------------
# Quick-validation entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sqlite3
    from config import DB_PATH, NBA_TEAM_MAP

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    try:
        clusters = get_all_team_clusters(conn)
        print(f"Team cluster assignments ({len(clusters)} teams):")
        for team_id, cluster_id in sorted(clusters.items(), key=lambda x: x[1]):
            abbrev = NBA_TEAM_MAP[team_id]["abbrev"]
            name = get_cluster_name(cluster_id)
            print(f"  {abbrev}: Cluster {cluster_id} — {name}")
    finally:
        conn.close()
